const funcName = async () => {

try {}
catch (whatever comes from try if try don't works) {}


}